---
server:
  name: "aap"
  admin_password: "redhat123"

managed:
  - name: lin1
    group: linux

  - name: lin2
    group: linux

  - name: win1
    group: windows
    box: "slu/win11"
    communicator: :winrm
    boot_timeout: 1800

  - name: win2
    group: windows
    box: "slu/win11"
    communicator: :winrm
    boot_timeout: 1800
