- name: Add Machine Credential for Lab to AAP
  hosts: automationcontroller
  connection: local
  tasks:
    - name: Create or update machine credential
      ansible.controller.credential:
        name: "Lab Credential"
        description: "SSH machine credentials for AAP lab"
        organization: "Default"
        credential_type: "Machine"
        inputs:
          username: "vagrant"
          password: "vagrant"
          #ssh_key_data: "{{ lookup('file', '~/.ssh/id_ed25519') }}"
        state: "present"
        controller_host: "https://aap.shared"
        controller_username: "admin"
        controller_password: "{{ controller_admin_password }}"
        validate_certs: no

